### ISSUE TITLE
Create a user friendly navbar and add logo of amazon  with responsiveness navbar should be visible on every page create a navbar same as amazon's website

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#1]
After making the changes create a video showing the navbar is visible on all tabs that are created

**Comment by varunsehgal02** [comment]
Hey maintainers. I want to work on this issue

**Comment by SanikaSalunkhe1** [comment]
hey maintainers , i would like to work on this issue plz assign to me

**Comment by Parth-code286** [comment]
Hey maintainer , i want to work on this issue

**Comment by Aditya-jambhale** [comment]
> Hey maintainers. I want to work on this issue

work on it and try to complete it asap

**Comment by varunsehgal02** [comment]
https://github.com/user-attachments/assets/ed87ed9a-3556-4168-8251-99f02ef3f16f
here is the video of navbar as asked for , let me know if any changes are required

**Comment by Aditya-jambhale** [comment]
> https://github.com/user-attachments/assets/ed87ed9a-3556-4168-8251-99f02ef3f16f here is the video of navbar as asked for , let me know if any changes are required
yes it is okay check the responsiveness for mobile view and create a pr and make sure that for all the pages the navbar stays same , attach the video for the same while creating the pr
