### ISSUE TITLE
Create a UI for home page add some cards or slider for showing accesories or any other products and it should be responsive 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#2]
![Screenshot 2024-10-06 021658](https://github.com/user-attachments/assets/290ea97d-fe59-4ac1-90f3-4e715c10ccc4)
this is a example of slider 
![Screenshot 2024-10-06 021819](https://github.com/user-attachments/assets/b5ad3655-0eb0-4477-aa3d-d67d20c7d7cd)
this is an example for cards

**Comment by SanikaSalunkhe1** [comment]
hello maintainers i want to work on this issue

**Comment by Parth-code286** [comment]
Hey maintainer , i want to work on this issue

**Comment by Aditya-jambhale** [comment]
> hello maintainers i want to work on this issue

Work on it and complete it asap
