### ISSUE TITLE
Create a responsive contact us page 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#28]
Upload your output image here !

**Comment by subhamagarrwal** [comment]
kindly assign me the issue, ill work and give you the output

**Comment by ghost** [comment]
Hi maintainer, would u pls assign me this issue !!

**Comment by SanikaSalunkhe1** [comment]
can u assign me this issue?

**Comment by nikamroshan** [comment]
Hey maintainer i want to work on this issue

**Comment by ghost** [comment]
I have designed the Responsive Contact us page for the website. The images for the same are as follows: 

1. The website Design -->
**![website design ](https://github.com/user-attachments/assets/6f1c7e85-fd91-4c3a-b0a6-f09676cfeeb0)**


2. Information Filling -->
![info fill](https://github.com/user-attachments/assets/0e657ffd-03ca-4e9d-bea0-9b5d32d1a063)


3. Once I click the Submit Button, A pop-up message appears -->
![request submitted](https://github.com/user-attachments/assets/2beae393-25c6-4ef6-8fd4-88baa27ea23b)


4. An error message appears if i unanimously click the Submit button without filling anything -->
![error message](https://github.com/user-attachments/assets/5d34bc41-8d07-4573-97bb-fc8852996beb)
