### ISSUE TITLE
FIx the Home page and make it responsive add some products images in home page"refer Amazon website"

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#29]
![image](https://github.com/user-attachments/assets/d4633890-8788-4bd6-925c-c381229ba8a9)
after solving upload a video here !

**Comment by AKASH7233** [comment]
can i work on it ?

**Comment by nupurnigudkar9404** [comment]
hey maintainer ,I want to solve this problem

**Comment by Aditya-jambhale** [comment]
> hey maintainer ,I want to solve this problem

work on it

**Comment by pratham145** [comment]
> ![image](https://private-user-images.githubusercontent.com/145918039/375547365-d4633890-8788-4bd6-925c-c381229ba8a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4Nzk4ODMsIm5iZiI6MTcyODg3OTU4MywicGF0aCI6Ii8xNDU5MTgwMzkvMzc1NTQ3MzY1LWQ0NjMzODkwLTg3ODgtNGJkNi05MjVjLWMzODEyMjliYThhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwNDE5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWNhNDIyMjA1NDhiNWNiZjZmNTdiNDUxYjMwNmQ2MDI5MDA1ZDQwYjBmZmUxNmEyNmYzOTM2MDgzZWJiMjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ML0HjYGwFp59qDZj7VhgwFptc5_z8yNSEkdQbq7tdqg) after solving upload a video here !
can i work on it?
