### ISSUE TITLE
Create ui for products page add some cards and slider for accessories ,clothes and watches,laptops with add to cart button with some hover effects

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#3]
![Screenshot 2024-10-06 022429](https://github.com/user-attachments/assets/6c1f273a-d708-4056-af3d-b7c27285939a)

https://github.com/user-attachments/assets/a29fe09b-168c-474d-870f-66fbe4a600d3
add some video or image of your output while raising pr

**Comment by SanikaSalunkhe1** [comment]
hey maintainers , i would like to work on this issue

**Comment by Parth-code286** [comment]
Hey maintainer , i want to work on this issue

**Comment by Aditya-jambhale** [comment]
> Hey maintainer , i want to work on this issue

Complete it asap

**Comment by ReshmaZore** [comment]
Heyy Maintainer , I want to work on this issue

**Comment by Rockyoudead8** [comment]
hey maintainer can you assign this issue to me
