### ISSUE TITLE
#Improve Page Background and Header

### ISSUE THREAD

**Issue by prakruthiprasad20** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#30]
- Change the header background to a dark blue color (`#232f3e`) similar to Amazon's navbar.
- Update link hover color in the header and footer orange (`#ff9900`).
- Set the main content background to white for a clean, minimalist look.
- Add a light grey (`#eaeaea`) background to the body, enhancing readability.

**Comment by pratham145** [comment]
can i work on it

**Comment by SanikaSalunkhe1** [comment]
hey maintainer can u assign me this issue?
