### ISSUE TITLE
#Adding a search bar

### ISSUE THREAD

**Issue by prakruthiprasad20** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#31]
Adding a functional and visually appealing search bar. A proper search bar is essential for improving user experience and navigation. .
And aslo to design it with css.

**Comment by SanikaSalunkhe1** [comment]
hey maintainer can u assign me this issue?

**Comment by KhanjarSingh** [comment]
@prakruthiprasad20 Can you please assign this issue to me?

**Comment by govindrajputFST** [comment]
Hii sir can you please assign this issue to me @prakruthiprasad20
