### ISSUE TITLE
add Rate us page

### ISSUE THREAD

**Issue by Sahoobarsharani** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#39]
please assign this to me under hacktoberfest2024

**Comment by ReshmaZore** [comment]
Heyy maintainer , I would like to work on this issue

**Comment by TechMe103** [comment]
Hey maintainer can you assign me this issue?

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue

**Comment by Parth-code286** [comment]
Hello maintainers I want to work on this issue

**Comment by Parth-code286** [comment]
Hello maintainers I want to work on this issue
