### ISSUE TITLE
Create a user friendly responsive login page with some hover effect 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#4]
Add you output image or video while raising the pr

**Comment by SanikaSalunkhe1** [comment]
hey  maintainers i want to solve this issue .plz assign to me this issue

**Comment by SanjanaSaw** [comment]
hey maintainers, can i work on this issue

**Comment by Aditya-jambhale** [comment]
> hey maintainers, can i work on this issue

Complete it asap

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue

**Comment by YashBawari18** [comment]
Hello maintainers I want to work on this issue
