### ISSUE TITLE
Create a responsive Back to Top button 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#40]

**Comment by shawaiz-khan** [comment]
I want to do this

**Comment by sajithcode** [comment]
can you assign me

**Comment by SanikaSalunkhe1** [comment]
Hey maintainer can I work on this issue?

**Comment by Naumantamboli** [comment]
i want to work on this issue, assign me this

**Comment by AadishSanghai** [comment]
hey @Aditya-jambhale  i want to work on this issue

**Comment by Aditya-jambhale** [comment]
> Hey maintainer can I work on this issue?

go for it and complete it asap
