### ISSUE TITLE
Fix the signup page and follow amazon's website color code

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#41]
![image](https://github.com/user-attachments/assets/1a62bc93-429c-48f7-9687-dd6e59ee00f0)

**Comment by shawaiz-khan** [comment]
Can I do this?

**Comment by sajithcode** [comment]
Could you please assign me

**Comment by SanikaSalunkhe1** [comment]
Hey maintainer can I work on this issue?

**Comment by QUBITABHAY** [comment]
Please assign me for this work.

**Comment by AadishSanghai** [comment]
i want to contribute to solve this issue please assign me this issue.

**Comment by SanjanaSaw** [comment]
Hey maintainer can I work on this issue?

**Comment by Aditya-jambhale** [comment]
> Hey maintainer can I work on this issue?

Go for it

**Comment by Raghavg18** [comment]
could you assign me to this issue i would like to contribute in this issue
