### ISSUE TITLE
Fix the product page and add some images of products 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#42]
![image](https://github.com/user-attachments/assets/a63b7c5f-4ae4-4ac1-b7f4-25ae50de3508)

**Comment by shawaiz-khan** [comment]
Can I contribute?

**Comment by SanikaSalunkhe1** [comment]
Hey maintainer can I work on this issue?

**Comment by AadishSanghai** [comment]
i want to contribute to solve this issue please assign me this issue.

**Comment by Lakshita-Kumawat** [comment]
I would like to contribute

**Comment by nupurnigudkar9404** [comment]
hey maintainer assign me this issue

**Comment by Aditya-jambhale** [comment]
> hey maintainer assign me this issue

work on it
