### ISSUE TITLE
Create a user friendly signup page 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#5]
Add your output image or video while raising the pr

**Comment by SanikaSalunkhe1** [comment]
hello maintainers plz assign to me this issue

**Comment by nupurnigudkar9404** [comment]
Hey maintainer, I want to work on this issue

**Comment by Aditya-jambhale** [comment]
> Hey maintainer, I want to work on this issue

Start working on it and complete it asap

**Comment by atharvamulam** [comment]
Hey @Aditya-jambhale ,

I’ve created a PR for the issue and attached a screenshot of the output for your review. Thank you for the opportunity to work on this!

Looking forward to your feedback!

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue

**Comment by Aditya-jambhale** [comment]
> Hello maintainers I want to work on this issue

Start working on it and try to complete asap

**Comment by Rockyoudead8** [comment]
hey maintainers can you assign this issue to me

**Comment by SanikaSalunkhe1** [comment]
hey maintainer i would like to work on this issue?
