### ISSUE TITLE
Fix the products page add Good CSS and remove the extra content 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#58]
https://github.com/user-attachments/assets/5200c1b0-bf42-42b3-9aff-08536f834fa3

**Comment by larrikin-coder** [comment]
assign me this issue @Aditya-jambhale

**Comment by YashBawari18** [comment]
Hey maintainer, kindly assign this issue to me

**Comment by nupurnigudkar9404** [comment]
Hey maintainer assign this issue to me

**Comment by Aditya-jambhale** [comment]
> Hey maintainer assign this issue to me
go for it

**Comment by YashBawari18** [comment]
hey maintainer , please assign me this issue
