### ISSUE TITLE
Fix the contact us page remove the old css and attach new one with good css and animations

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#59]
![image](https://github.com/user-attachments/assets/13d0d82b-61f1-4ce5-b2dc-21373b6c2665)

**Comment by larrikin-coder** [comment]
please assign me this @Aditya-jambhale

**Comment by SanikaSalunkhe1** [comment]
hey maintainer can u assign me this issue

**Comment by Aditya-jambhale** [comment]
> hey maintainer can u assign me this issue

go for it

**Comment by YashBawari18** [comment]
hey maintainer , please assign me this issue

**Comment by YashBawari18** [comment]
hey maintainer , please assign me this issue
