### ISSUE TITLE
Create a responsive Footer for all tabs 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#6]
Add the image output or video while raising the pr

**Comment by VaradDhoke** [comment]
Hey Maintainer, I'd like to solve this issue.

**Comment by SanikaSalunkhe1** [comment]
hey maintainers , i want to solve this issue

**Comment by nikamroshan** [comment]
Hey maintainer , i want to work on this issue

**Comment by Aditya-jambhale** [comment]
> Hey maintainer , i want to work on this issue

Okay go for it and try to complete asap

**Comment by Vikas3100** [comment]
Please assign me this issue

**Comment by kartik3165** [comment]
> Please assign me this issue
listen bro fork this branch in code space or locally edit the code and push the request
