### ISSUE TITLE
Fix the CSS of all the pages "enhancement of Website"

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#61]
Try to add some new css with exact responsiveness and also animations if possible:)

**Comment by YashBawari18** [comment]
Hey maintainer, kindly assign this issue to me

**Comment by shiv-0101** [comment]
Hey Adi

Need to add css to any one page or all the pages? 

(If all the pages, should we go with multiple PRs?.....what do u think?)

**Comment by Raghavg18** [comment]
hey Adi 
kindly assign me this issue to me

**Comment by ghost** [comment]
Hi Maintainer ! Would u please assign me this issue

**Comment by Aditya-jambhale** [comment]
> Hi Maintainer ! Would u please assign me this issue

Go for it
