### ISSUE TITLE
Fix the Contact us page

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#68]
![image](https://github.com/user-attachments/assets/a443d71c-f046-4795-b83a-cbcd2daed062)
Fix the navbar in the contact us page it should be same as other page have one .

**Comment by AdityaInnovates** [comment]
Hello, I would like to work on the issue.

**Comment by dexterousdhruv** [comment]
Could you assign it to me ? I'd like to work on this one.

**Comment by ishan657** [comment]
Hy @Aditya-jambhale 
I have understood the issue well and I'm eager to work on this issue 
Kindly assign me this issue and I can guarantee to finish quality work on time 
Thank you

**Comment by ghost** [comment]
Hi Maintainer ! Would u pls assign me this issue

**Comment by Aditya-jambhale** [comment]
> Hi Maintainer ! Would u pls assign me this issue

go for it!
