### ISSUE TITLE
Add a functionality of Add to cart 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#7]
upload image of output or video

**Comment by VaradDhoke** [comment]
Hey maintainers, I want to solve this issue.

**Comment by SanikaSalunkhe1** [comment]
hello maintainers , i want to solve this issue plz assign to me

**Comment by Aditya-jambhale** [comment]
> Hey maintainers, I want to solve this issue.

go for it try to complete it asap

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue
