### ISSUE TITLE
Make The Navbar Exactly Like The Amazon.in

### ISSUE THREAD

**Issue by anuragkumart16** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#70]
Clone's present navbar doesn't look alike the original's navbar, assign me this issue and I will edit the navbar making it completely alike the navbar of Amazon.

- I will fix the Logo.
- I will fix the update location section of navbar.
- I will bring the search bar in center and reduce its size.
- I will edit the section post search bar making it exactly like amazon.in

Kindly Assign me this issue and also add hactoberfest-accepted and hactoberfest tags.
Regards 

Anurag
<img width="1481" alt="Screenshot 2024-10-23 at 12 16 38 PM" src="https://github.com/user-attachments/assets/02f70067-3aa0-4585-9b20-c961bdf3a2e9">
<img width="1481" alt="Screenshot 2024-10-23 at 12 16 47 PM" src="https://github.com/user-attachments/assets/1279f1b2-dd4d-4bf4-991b-6d2f923f835e">

**Comment by govindrajputFST** [comment]
Sir can you please assign this issue to me @anuragkumart16
