### ISSUE TITLE
Add responsive "Search bar" in nav bar 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#8]
upload the image of output or video

**Comment by SanikaSalunkhe1** [comment]
hey maintainers , can i work on this issue..? plz assign to me

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue

**Comment by Shreyashjadhav1001** [comment]
Hello maintainers, I want to work on this issue.

**Comment by Shreyashjadhav1001** [comment]
Hello maintainers, I want to work on this issue.

**Comment by AdK819** [comment]
Hello Maintainer! Aditi here
May I work on this issue?

**Comment by Vikas3100** [comment]
Please assign me this issue

**Comment by dexterousdhruv** [comment]
@Aditya-jambhale  I have raised a PR #13  regarding the concerned issue. Please review it and merge it.

**Comment by Aditya-jambhale** [comment]
> Hello Maintainer! Aditi here May I work on this issue?

yes go for it but please click on sync button on your repo after forking the repository as the changes made by other people will be visible to you and complete it asap

**Comment by dexterousdhruv** [comment]
@Aditya-jambhale  Could you just check my PR since the original assignee hasn't responded yet ?

**Comment by dexterousdhruv** [comment]
@Aditya-jambhale  What about now ?

https://github.com/user-attachments/assets/4b5f45c5-2711-4312-8188-ff30f106e904
