### ISSUE TITLE
create a "404 Not found page" as a functionality whenever user goes to a undefined route 404 page should be rendered

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Amazon-Hacktoberfest2024#9]
Add the video of your output

**Comment by SanikaSalunkhe1** [comment]
hello maintainers , i want to work on this issue

**Comment by Khanvilkarshravani27** [comment]
Hello Maintainer , Can I work on this issue?

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue

**Comment by Aditya-jambhale** [comment]
> Hello Maintainer , Can I work on this issue?

start working on it complete it asap

**Comment by Nishankulal03** [comment]
Hello Maintainer i really want to work on this issue
